### ISSUE TITLE
Charm notch costs suddenly went way up

### ISSUE THREAD

**Issue by argon932** [dpinela/Transcendence#12] opened 2022-05-26 23:13 UTC
I found a bunch of the new charms today and they were all 1-4 notch costs. Now the next day I went to go play and they are all 5-6 notch costs on the same save. Didn't make any changes. Seems like something is changing them after save reload maybe.

I am using randomized, with charm notch costs randomized, and in the randomizer settings for Transcendence I set new max charm cost to "0" because I don't want any charms costing more than 6 (which is already a ridiculous cost IMO). This seems like a bug to me. 

I think what is happening is on save reload, the mod overwrites whatever randomize sets as it's random notch costs.

![image](https://user-images.githubusercontent.com/99354959/170594038-21c74d66-bff4-43fc-ab1e-a71e16575813.png)

**Comment by dpinela** [comment] 2022-05-26 23:23
I will look into this. It's not the first time I've heard of this kind of issue but I have not been able to reproduce it yet.

About the "IncreaseMaxCharmCostBy", that doesn't affect the notch cost of the charms, but rather the limit on the amount of charms you may need to have to buy something from Salubra (it's there so you can raise it past 40 if you want). Admittedly the term "charm cost" may be ambiguous, but it's also what the randomizer itself uses to describe those charm thresholds.

**Comment by argon932** [comment] 2022-05-26 23:25
I bought a charm from a vendor, saved, reloaded, still 2 notches... so I am not sure what's triggering it :(

**Comment by dpinela** [comment] 2022-05-26 23:38
I tried making a new randomizer save, looking at the costs, and reloading (even closing the game entirely in the middle), but I am still unable to replicate this issue.

As for fixing the costs, you can manually edit your userX.modded.json file (where X is the slot the save is on), under the "Transcendence" section. You'll find a bit that looks like this:

```"Transcendence": {
      "AntigravityAmulet": {
        "Got": true,
        "Equipped": false,
        "New": false,
        "Cost": 3
      },
      "BluemothWings": {
        "Got": true,
        "Equipped": false,
        "New": false,
        "Cost": 3
      },
```

To change the costs, you just need to edit those cost values. Bear in mind that this json file also contains a list of all the item placements rando made, just like the spoiler log, so be sure 🙈 or ctrl+f past that part!

**Comment by argon932** [comment] 2022-05-26 23:44
I will see if I can reproduce it as I play further. I made no changes while playing, made the save earlier today with 3 hours currently played. At some point the charms just increased in cost. I did have 1 crash (which is odd because I have never crashed in unmodded hollow knight). This is my first randomizer game.

**Comment by xXmegagallade** [comment] 2022-05-27 13:38
This is happening to me too, every time I initiate a randomizer all of the charms from this mod will have 6 cost. Ive tried 4 times with trying out different randomizer settings and no dice, they always cost 6. heres a screenshot of my mods list in case that helps
![Capture](https://user-images.githubusercontent.com/106389275/170710469-d5bb1537-aba8-464a-a921-dd70edb6a6d3.PNG)
.

**Comment by argon932** [comment] 2022-05-27 23:54
Mine definitely don't cost 6 notches at the start (with charm notch cost randomed), I tried and the most expensive was 4 looking at my save game file and cheating in the charms. However looking at my save that's 4 hours old, 5 of the new charms cost 6 notches, and a few others cost 5, when they did not at the start of the run. I'm positive because I was using a charm at the start that cost 2, when I had 3 notches, now it cost 6 and I cannot use it anymore without save edit.

I have a theory that randomizer is re-randomizing the notch costs for transcendence charms in middle of playthrough. The way randomizer factors in notch cost is not totally random, it takes all of the charms and spreads out a randomized set number of notches across all of them. So with Transcendence installed, notch costs across the board are "likely" cheaper because there are more charms. It's possible at some point it is re-randomizing charm notch costs in the middle of the run but only for Transcendence charms, which means their costs would end up being very expensive cause it's spreading notches for 40 charms across 12 charms.

**Comment by dpinela** [comment] 2022-05-29 02:13
That theory is incorrect. The randomizer's notch cost randomization code only applies to the 40 base charms; the cost randomization for Transcendence's charms is actually done by Transcendence itself, using a separate pool of notches from the randomizer, when a new file is started. This is supposed to occur only once per file; I have suspected that the relevant code might be getting called multiple times but have never been able to get that to happen.

Speaking of which, does anyone have a ModLog from a session where this bug happened? There is some logging in the mod that I put in to validate that hypothesis.

**Comment by Thingw31** [comment] 2022-07-03 21:19
What caused this for me, was increasing how many charm notches i have past the normal obtainable amount, that is what triggered the notches to become 5-6 cost on my 2 runs.

**Comment by dpinela** [comment] 2022-10-27 00:57
I have not seen any more reports of this recently, and I have a suspicion as to what caused it which leads me to think it's likely fixed for good.

**Closed by dpinela** 2022-10-27 00:57 UTC
